baseURL = "https://www.bucadibeppo.com/"
languageCode = "en-us"
title = "Buca di Beppo Italian Restaurant"

[deployment]

[[deployment.targets]]
name = "prod"
URL = "s3://buca-di-beppo"
#cloudFrontDistributionID = "E23JC8KW19KR5P"

# Azure Blob Storage; see https://gocloud.dev/howto/blob/#azure
# URL = "azblob://$web"

